go_import_path: github.com/pomerium/viper

language: go

env:
  global:
    - GO111MODULE="on"
    - GOFLAGS="-mod=readonly"

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go install ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -race -v ./...
